Fix layout

diff --git a/.github/workflows/azari-build.yml b/.github/workflows/azari-build.yml
--- a/.github/workflows/azari-build.yml
+++ b/.github/workflows/azari-build.yml
@@ -26,7 +26,7 @@ jobs:
         run: |
           test -n "${{ secrets.VM_HOST }}" || (echo "VM_HOST is missing" && exit 1)
           test -n "${{ secrets.VM_USER }}" || (echo "VM_USER is missing" && exit 1)
-          test -n "${{ secrets.VM_SSH_KEY }}" || (echo "VM_SSH_KEY is missing" && exit 1)
+          test -n "${{ secrets.VM_SSH_PRIVATE_KEY }}" || (echo "VM_SSH_PRIVATE_KEY is missing" && exit 1)
 
       - name: Install dependencies
         run: npm ci
@@ -37,7 +37,7 @@ jobs:
       - name: Setup SSH
         run: |
           mkdir -p ~/.ssh
-          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
+          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
           ssh-keyscan -p ${{ secrets.VM_PORT || '22' }} ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
